### PR TITLE
Work plan template

### PR DESCRIPTION
**Pull request by woodbe**
Created from template provided by @mmbarry

Some modification based on ordering (cPP before SD, for example).

Probably needs more stuff about maintenance/interpretations than a single line at the end, but can be considered later

### CODE REVIEW

**Comment by mmbarry** [comment]
Hi Brian, 
I have 2 comments
- the 2 tasks; Draft SPD approved by iTC and Draft SPD comments reviewed by iTC should be reversed and I had it wrong in our workplan as well.  Usually the draft SPD would be created by a subset of iTC participants and then sent out for comment within the iTC.  Those comments would be reviewed within the iTC, SPD approved and then sent out for public comment.
- my second comment is regarding the publishing of the SD for public review and it's subsequent approval.  The CCRA guidance is very weak here and I believe this is outstanding for this process.  For example, there are NO SDs approved right now.  The guidance doesn't state that the SD has to be posted for public review, but rather states "The documents distributed for review may also include any relevant parts of Supporting Documents that are available, or that are necessary to review the SFRs." in block 19 - which is publishing requirements (SFRs) for review.   I am thinking we should just 'ignore' this, but wanted to highlight it to you for your input.  
Thanks!

**Comment by woodbe** [comment]
I made changes based on @mmbarry comments. The SPD tasks were re-ordered correctly (good catch).

As for the SD, what I did was remove the explicit evaluation and certification rows for the SD. I did add the SD to the certification line for the cPP as the first evaluation to the cPP would also be when the SD would be evaluated, so I thought that was appropriate. 

Brian

**Comment by mmbarry** [comment]
I think this works well Brian.  I will go ahead and approve - thanks!

**Comment by mmbarry** [comment]
It would be great to see this updated - thanks!

**Pull request merged**
