### PR TITLE
Initial template for invitation letter

### PR DESCRIPTION
**Pull request by woodbe**
Took blank from @mmbarry

Added variable names at beginning, slight tweaks

### CODE REVIEW

**Comment by mmbarry** [comment]
I only found one very small error....link for creating cPP document didn't work.  The correct link is https://www.commoncriteriaportal.org/files/communities/Establishing%20iTCs%20and%20cPP%20development%20-%20v0-7.pdf

**Comment by woodbe** [comment]
URL has been fixed.

**Comment by mmbarry** [comment]
I grabbed a glass of water and poof - it is fixed.  Closing as approved...I think this is how it works.  Let me know if not - thanks!

**Comment by woodbe** [comment]
I reopened it, you need to click on the Approve like here:

https://github.com/itc-wgtools/cPP-Tools/blob/develop/User%20Guidance/userguide.adoc#approving-pull-requests

**Pull request merged**
