### PR TITLE
Update for vote counting

### PR DESCRIPTION
**Pull request by woodbe**
I have made changes here trying to make vote counting clearer.

### CODE REVIEW

**Comment by woodbe** [comment]
This is related to #28 for the voting counts. I have tried to make it clearer exactly how to count the votes by creating a category of votes called "counted votes". This has its own definition (that the votes must be one of the listed categories) to be included in the final count.

I still have these questions though:

1. If someone submits a negative vote with a reason and that reason is fixed and no one else objects, does this require a new vote (this really shouldn't happen since any objections should have been raised before, but given that some people who may not participate regularly may read things and then vote, this is likely to happen). This is really only a question when the negative votes are on the edge, so maybe this isn't really an issue since it is rare and what you should do is take the No and continue working.
2. Should there be a period of time between votes? For example a vote just went negative, if the issue is a quick fix, can a new vote be called quickly or does there need to be a "cooling off" period before a new vote?
3. If multiple people from an organization vote and the votes are different (i.e. one goes positive, the other negative), obviously it is up to the organization to figure out what their vote needs to be, but what is the obligation of the iTC to inform them? If they both vote the same, then it doesn't really matter, count it as one vote, but when they are not the same, is the expectation that the iTC ballot counter is actively monitoring the votes to let them know? I put in a note that in this case the votes can be adjusted during the open ballot period but left open anything about notification and such.

**Comment by woodbe** [comment]
Click on the Files Changes tab on the top of this thread, and then on the right side of that screen click the 3 dots and select View file. You will need to do the pen thing to edit after that (to see it wrapped).

View File

**Comment by ansukert** [comment]
Brian,

Another “newbie to GitHub” question. When I try to do the “pen thing” it says that I have to be in a branch to do that. How do I get to a branch?

Alan

**Comment by woodbe** [comment]
Look at the left hand side and select "voting edits" from the dropdown list (the list is alphabetical).

image

**Comment by ansukert** [comment]
I figured it out. Thanks.

Alan

**Comment by woodbe** [comment]
I am closing (and deleting) this PR. I have moved my questions into #35 and have integrated these changes into the main PR for the ToR because of the issue with the binary code in the original file.

**Pull request closed without merging**
